### NumPy Arrays
##### They are either 1-d or 2-d

In [1]:
import numpy as np

In [3]:
#Create a list
my_list = [1,2,3]
#Convert it into an array using numpy
arr = np.array(my_list)
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
twoDArr = np.array(my_mat)
twoDArr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
#Using np inbuilt array generation method instead
#of creating a list first
np.arange(0,10) #This returns an array with values 
#from 0-10. I can also pass a third argument to the 
#arrange function to specify the stepping value.


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.zeros(3)#this generates a 1d array of 0 with 3values


array([0., 0., 0.])

In [8]:
np.zeros((5,5))#this generates a 2d array of 0 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [11]:
#linspace returns an array with the number of the 
#specified third argument evenly spaced values
np.linspace(0,5,10)#this code returns an array of 10
#evenly spaced values between 0 and 5

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [12]:
#Identity matrix, this is used to generate a 2d array
#this contains a diagonal row of 1s with remaining values
#being 0. The returned array has equal size
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
#np random generates an array with random values.
#it has different methods 
np.random.rand(5)#this generates a 1d array of random
#values between 0 and 1

array([0.48044144, 0.71176668, 0.78760633, 0.88526333, 0.6932634 ])

In [14]:
np.random.rand(5,5)#this generates a 2d

array([[0.91184124, 0.13034607, 0.26502849, 0.37540006, 0.8570231 ],
       [0.50307854, 0.46444015, 0.57009725, 0.84486616, 0.82363553],
       [0.47859151, 0.07988963, 0.78757767, 0.78270985, 0.9270861 ],
       [0.83606886, 0.86161658, 0.62969344, 0.90459371, 0.48277072],
       [0.37584918, 0.26929253, 0.61679015, 0.28823943, 0.49396931]])

In [16]:
np.random.randn(2,2)#returns an array with a standard normal distribution

array([[-0.14711847,  0.76098753],
       [ 0.07364372,  0.03743233]])

In [17]:
np.random.randint(1,100,10)#this returns an array of 10 
#random int between 1 and 100 (i.e from low to high)

array([19, 45, 65, 21, 74, 57, 52, 29, 79, 22])

In [18]:
np.random.randint(1,100)#this returns a random int
#btwn 1 and 100

73

In [20]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [21]:
ranarr = np.random.randint(0,50,10)
ranarr

array([ 1,  4, 26, 15,  1,  8, 32, 48, 26, 41])

In [23]:
#I can reshape an array to a desired shape
arr.reshape(5,5)#arr will be reshaped to a 5X5 matrix
#Note that the product of the no of rows and columns
#specified to the reshape method must be equal to the
#number of elements in the array I am passing to it

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
ranarr.max()

48

In [25]:
ranarr.min()

1

In [26]:
ranarr.argmax()#this returns the index location of the max value

7

In [29]:
arr.shape #returns the shape of the array

(25,)

In [31]:
arr.dtype #this returns the data types in an array

dtype('int32')

### Continued in my notebook